### ISSUE TITLE
Combination with Shell

### ISSUE THREAD

**Issue by mycroes** [arvindd/MauiAppSample#1]
I'm missing integration with MAUI's `Shell`. I think the Shell is a nice MAUI feature, but I'm not sure if there are any caveats if one would combine Shell with the `RoutedViewHost` from ReactiveUI? Will Shell replace the `RoutedViewHost` on navigation?

Other than that thanks for this project, I think it's a good starter for MAUI+ReactiveUI.

**Comment by arvindd** [comment]
Sorry, could not find time to add that until now... updated the sample using AppShell.
